title        = "Tekton Pipelines"
baseURL      = "https://tekton-dev.netlify.com"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
favicon = "favicon.png"
subtitle = "A Kubernetes-native pipeline resource"
github   = "https://github.com/tektoncd/pipeline"

[params.logos]
navbar = "horizontal-color"

[params.fonts]
sansserif = "Franklin Gothic Heavy Regular"
