title        = "Tekton Pipelines"
baseURL      = "https://tekton-dev.netlify.com"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
favicon = "favicon.png"
subtitle = "Foo"

[params.logos]
navbar = "horizontal-color"

[params.fonts]
sansserif = "Franklin Gothic Heavy Regular"
